%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\arjun\OneDrive\Desktop\Table4_9.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2022/06/30 17:51:52

%% Import the data
[~, ~, raw] = xlsread('C:\Users\arjun\OneDrive\Desktop\Table4_9.xlsx','Sheet1','A2:C21');

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
Table49 = table;

%% Allocate imported array to column variable names
Table49.FNSet1 = data(:,1);
Table49.FNSet2 = data(:,2);
Table49.FNSet3 = data(:,3);

%% Clear temporary variables
clearvars data raw;